### ISSUE TITLE
编译不了

### ISSUE THREAD

**Issue by he426100** [drunkard/ceph-Chinese-doc#1]
`
ERROR: Invalid requirement: 'src/python-common' (from line 1 of /home/mrpzx/git/ceph/admin/doc-python-common-requirements.txt)
Hint: It looks like a path. File 'src/python-common' does not exist.
`

`
/home/mrpzx/git/ceph/build-doc/virtualenv/bin/python: can't open file '/home/mrpzx/git/ceph/doc/scripts/gen_mon_command_api.py': [Errno 2] No such file or directory
`

**Comment by drunkard** [comment]
路径不对，我这里部署的是 /git/ceph 下。你可以做个软链接，再看看。
有些路径是写死的，以后慢慢改进吧。
